import Foundation

nonisolated public extension Pokemon {
    static var sample: Pokemon {
        Self.samples.first!
    }
    
    static var samples: [Pokemon] {
        [
            Pokemon(id: 1, name: "bulbasaur", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png")!), flavorText: "A strange seed was planted on its back at birth. The plant sprouts and grows with this POK\u{e9}MON."),
            Pokemon(id: 2, name: "ivysaur", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png")!), flavorText: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs."),
            Pokemon(id: 3, name: "venusaur", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png")!), flavorText: "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight."),
            Pokemon(id: 4, name: "charmander", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png")!), flavorText: "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail."),
            Pokemon(id: 5, name: "charmeleon", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png")!), flavorText: "When it swings its burning tail, it elevates the temperature to unbearably high levels."),
            Pokemon(id: 6, name: "charizard", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png")!), flavorText: "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally."),
            Pokemon(id: 7, name: "squirtle", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png")!), flavorText: "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth."),
            Pokemon(id: 8, name: "wartortle", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png")!), flavorText: "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance."),
            Pokemon(id: 9, name: "blastoise", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png")!), flavorText: "A brutal POK\u{e9}MON with pressurized water jets on its shell. They are used for high speed tackles."),
            Pokemon(id: 10, name: "caterpie", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png")!), flavorText: "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls."),
            Pokemon(id: 11, name: "metapod", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png")!), flavorText: "This POK\u{e9}MON is vulnerable to attack while its shell is soft, exposing its weak and tender body."),
            Pokemon(id: 12, name: "butterfree", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png")!), flavorText: "In battle, it flaps its wings at high speed to release highly toxic dust into the air."),
            Pokemon(id: 13, name: "weedle", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png")!), flavorText: "Often found in forests, eating leaves. It has a sharp venomous stinger on its head."),
            Pokemon(id: 14, name: "kakuna", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png")!), flavorText: "Almost incapable of moving, this POK\u{e9}MON can only harden its shell to protect itself from predators."),
            Pokemon(id: 15, name: "beedrill", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png")!), flavorText: "It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly."),
            Pokemon(id: 16, name: "pidgey", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png")!), flavorText: "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand."),
            Pokemon(id: 17, name: "pidgeotto", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png")!), flavorText: "Very protective of its sprawling territorial area, this POK\u{e9}MON will fiercely peck at any intruder."),
            Pokemon(id: 18, name: "pidgeot", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png")!), flavorText: "When hunting, it skims the surface of water at high speed to pick off unwary prey such as MAGIKARP."),
            Pokemon(id: 19, name: "rattata", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png")!), flavorText: "Bites anything when it attacks. Small and very quick, it is a common sight in many places."),
            Pokemon(id: 20, name: "raticate", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png")!), flavorText: "It uses its whis­ kers to maintain its balance. It apparently slows down if they are cut off."),
            Pokemon(id: 21, name: "spearow", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png")!), flavorText: "It flaps its small wings busily to fly. Using its beak, it searches in grass for prey."),
            Pokemon(id: 22, name: "fearow", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png")!), flavorText: "With its huge and magnificent wings, it can keep aloft without ever having to land for rest."),
            Pokemon(id: 23, name: "ekans", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png")!), flavorText: "Moves silently and stealthily. Eats the eggs of birds, such as PIDGEY and SPEAROW, whole."),
            Pokemon(id: 24, name: "arbok", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png")!), flavorText: "It is rumored that the ferocious warning markings on its belly differ from area to area."),
            Pokemon(id: 25, name: "pikachu", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png")!), flavorText: "When several of these POK\u{e9}MON gather, their electricity could build and cause lightning storms."),
            Pokemon(id: 26, name: "raichu", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png")!), flavorText: "Its long tail serves as a ground to protect itself from its own high-voltage power."),
            Pokemon(id: 27, name: "sandshrew", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png")!), flavorText: "Burrows deep underground in arid locations far from water. It only emerges to hunt for food."),
            Pokemon(id: 28, name: "sandslash", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png")!), flavorText: "Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape."),
            Pokemon(id: 29, name: "nidoran-f", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png")!), flavorText: "Although small, its venomous barbs render this POK\u{e9}MON dangerous. The female has smaller horns."),
            Pokemon(id: 30, name: "nidorina", sprites: Sprites(front_default: URL(string: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png")!), flavorText: "The female's horn develops slowly. Prefers physical attacks such as clawing and biting.")
        ]
    }
}
